name: First one
on:  [ push, workflow_dispatch ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run echo command
        run: echo "Hello Hello"
  checkout_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: nebhardw/msx-developer-guides
      - name: Checking out local repo
        uses: actions/checkout@v3
        with:
          repository: nebhardw/simple-java-maven-app
      - name: Running ansible lint
        uses: ansible/ansible-lint@main
  finish_all:
    needs: checkout_code
    runs-on: ubuntu-latest
    steps:
      - name: Finishing ubuntu_latest
        run: echo "All Done"
      - name: Github Context
        run: echo "${{ toJSON(github) }}"
